name: Setup Haskell
author: Simon Hengel

inputs:
  ghc-version:
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "$HOME/.ghcup/bin" >> "$GITHUB_PATH"
      if: runner.os == 'macOS'
    - shell: bash
      run: echo "ImageOS=$ImageOS" >> $GITHUB_ENV
    - shell: bash
      run: sudo apt-get update && sudo apt-get install -y libncurses5
      if: env.ImageOS == 'ubuntu22' && (inputs.ghc-version == '8.0.2' || inputs.ghc-version == '8.2.2')
    - shell: bash
      run: rm -rf /usr/local/.ghcup/*
    - shell: bash
      run: |
        dst=$RUNNER_OS-$ImageOS-$RUNNER_ARCH-ghc-${{ inputs.ghc-version }}.tar.gz
        gh release download nightly --repo hspec/setup-haskell -p "$dst" -O - | sudo tar -xzp -C /
      env:
        GH_TOKEN: ${{ github.token }}
