name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-10.15
          - windows-2022
          - windows-2019
          - windows-2016
        ghc:
          - 7.10.3
          - 8.0.2
          - 8.2.2
          - 8.4.1
          - 8.4.2
          - 8.4.3
          - 8.4.4
          - 8.6.1
          - 8.6.2
          - 8.6.3
          - 8.6.4
          - 8.6.5
          - 8.8.1
          - 8.8.2
          - 8.8.3
          - 8.8.4
          - 8.10.1
          - 8.10.2
          - 8.10.3
          - 8.10.4
          - 8.10.5
          - 8.10.6
          - 8.10.7
          - 9.0.1
          - 9.0.2
          - 9.2.1
          - 9.2.2

    steps:
      - uses: actions/checkout@v3
      - name: setup-haskell
        uses: ./
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: ghc --version
