name: selftest macos-15
on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 3 * *
  push:
    branches:
      - selftest
jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: setup-haskell
        uses: ./
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: ghc --version
      - run: cabal update
      - run: cabal install alex
      - run: alex --version
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
        ghc:
          - 9.2.5
          - 9.2.6
          - 9.2.7
          - 9.2.8
          - 9.4.2
          - 9.4.3
          - 9.4.4
          - 9.4.5
          - 9.4.6
          - 9.4.7
          - 9.4.8
          - 9.6.1
          - 9.6.2
          - 9.6.3
          - 9.6.4
          - 9.6.5
          - 9.6.6
          - 9.6.7
          - 9.8.1
          - 9.8.2
          - 9.8.4
          - 9.10.1
          - 9.12.1
          - 9.12.2
